name: prosvet
description: "Просвет — локальный Windows-клиент для точечного доступа к сервисам без системного VPN."
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.1
  pointycastle: ^4.0.0
  tray_manager: ^0.7.0
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray_on.ico
    - assets/tray_off.ico
    - assets/licenses/
